on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "before2"
        run: ls
      
      -uses: actions/checkout@v3

      - name: "after2"
        run: ls